From ubuntu
workdir /app
expose 8080
###cmd ["java", "-jar", "demo-0.0.1-SNAPSHOT.jar"]
cmd ["/app/script.sh"]
add scripts/script.sh /app/script.sh
add scripts/script.sql /app/script.sql
run apt-get update
run apt-get install -y mariadb-server
run apt-get install -y openjdk-8-jdk
run chmod 755 /app/script.sh
run /etc/init.d/mysql start; mysql < /app/script.sql
add app/practicas-0.0.1-SNAPSHOT.jar /app